name: app_de_bebidas
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  google_sign_in: ^6.3.0
  provider: ^6.1.4
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.0.15
  http: ^1.3.0
  google_maps_flutter: ^2.11.0
  geocoding: ^3.0.0
  excel: ^2.0.5
  path_provider: ^2.0.10
  json_annotation: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
