// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_htGumA1JK6UBrztXjIKUZCe4mvHMeik',
    appId: '1:469393720381:web:91f25ac5f3027635d0d654',
    messagingSenderId: '469393720381',
    projectId: 'app-de-bebidas-826aa',
    authDomain: 'app-de-bebidas-826aa.firebaseapp.com',
    databaseURL: 'https://app-de-bebidas-826aa-default-rtdb.firebaseio.com',
    storageBucket: 'app-de-bebidas-826aa.firebasestorage.app',
    measurementId: 'G-SKRXWSG1TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5DJ7rfU2oKM9bFr0m3Zu5HzC3nHitwfk',
    appId: '1:469393720381:android:76999e0cd2e04f1ed0d654',
    messagingSenderId: '469393720381',
    projectId: 'app-de-bebidas-826aa',
    databaseURL: 'https://app-de-bebidas-826aa-default-rtdb.firebaseio.com',
    storageBucket: 'app-de-bebidas-826aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyP2ypLY-f2wQMH5LRoO8vaAyMAp_VLw',
    appId: '1:469393720381:ios:3e786954cd7c3fffd0d654',
    messagingSenderId: '469393720381',
    projectId: 'app-de-bebidas-826aa',
    databaseURL: 'https://app-de-bebidas-826aa-default-rtdb.firebaseio.com',
    storageBucket: 'app-de-bebidas-826aa.firebasestorage.app',
    iosClientId: '469393720381-r6tbsoi1k9e76rfsp0v8g7ul70bqb8sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDeBebidas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUyP2ypLY-f2wQMH5LRoO8vaAyMAp_VLw',
    appId: '1:469393720381:ios:3e786954cd7c3fffd0d654',
    messagingSenderId: '469393720381',
    projectId: 'app-de-bebidas-826aa',
    databaseURL: 'https://app-de-bebidas-826aa-default-rtdb.firebaseio.com',
    storageBucket: 'app-de-bebidas-826aa.firebasestorage.app',
    iosClientId: '469393720381-r6tbsoi1k9e76rfsp0v8g7ul70bqb8sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDeBebidas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_htGumA1JK6UBrztXjIKUZCe4mvHMeik',
    appId: '1:469393720381:web:ced5ceb58a3a6a13d0d654',
    messagingSenderId: '469393720381',
    projectId: 'app-de-bebidas-826aa',
    authDomain: 'app-de-bebidas-826aa.firebaseapp.com',
    databaseURL: 'https://app-de-bebidas-826aa-default-rtdb.firebaseio.com',
    storageBucket: 'app-de-bebidas-826aa.firebasestorage.app',
    measurementId: 'G-M67CJK85NG',
  );

}